name: bayesevt_ai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  # - conda-forge::jupytext
  # - conda-forge::jupyter-book
  # - conda-forge::myst-parser
  # - conda-forge::pre-commit
  # - conda-forge::"nodejs>=20,<21"
  # - conda-forge::mystmd
  - conda-forge::regionmask
  - conda-forge::xarray
  # DATASETS
  - conda-forge::xmip
  - conda-forge::cf_xarray
  - conda-forge::intake-esm
  # STUFF
  - cudatoolkit
  # VISUALIZATION
  - cartopy
  - cmocean
  - seaborn
  - matplotlib
  - xmovie
  - ipykernel
  - ffmpeg
  - pip
  - pip:
      - cookiecutter
      - autoroot
      - python-dateutil
      - pydantic
      # DATA ACCESS
      - climetlab
      - xee
      - ecmwf-api-client
      - cdsapi
      - gcsfs
      # OTHER
      # VISUALIZATION
      # - lexcube
      - tqdm
      # ECMWF MODELS
      - ai-models
      # - ai-models-panguweather
      # - ai-models-graphcast
      # - ai-models-fourcastnet
      - ai-models-fourcastnetv2
      - git+https://github.com/NVIDIA/earth2mip.git
      - onnxruntime-gpu
      # - git+https://github.com/deepmind/graphcast.git
    #   - sphinx-proof
      - loguru 
