name: ai-models
channels:
  - conda-forge
dependencies:
  - python=3.10
  - cudatoolkit
  - conda-forge::iris
  - conda-forge::iris-grib
  - xarray
  - cartopy
  - cmocean
  - seaborn
  - matplotlib
  - xmovie
  - ipykernel
  - ffmpeg
  - pip
  - pip:
      # ECMWF MODELS
      - ai-models
      - ai-models-panguweather
      - ai-models-graphcast
      - ai-models-fourcastnet
      - ai-models-fourcastnetv2
      - git+https://github.com/deepmind/graphcast.git
      # VISUALIZATION
      - lexcube
      - tqdm
      - ecmwf-api-client
      - cds
